language: cpp
os:
  - linux
dist:
  - xenial
compiler:
  - gcc
  - clang
branches:
  only: ["master"]
install:
  - cd ${TRAVIS_BUILD_DIR}
  - ./scripts/install-deps.sh
  - ./scripts/tap.sh
script:
  - cd ${TRAVIS_BUILD_DIR}
  - meson build
  - cd build
  - meson configure -Dbuildtype=release -Db_sanitize=address,undefined
  - ninja test
  - ninja smoke
